### ISSUE TITLE
Setting frequency presets on website

### ISSUE THREAD

**Issue by TaVodic** [TaVodic/TLS_ETH_basic#1]
# Overview
- Working with EEPROM
- Setting from website
- Sending to website
- Setting HC-12

## TODO
- [x] read data from website, store the value
- [x] read EEPROM, write EEPROM
- [x] set HC-12 function
